<?xml version='1.0'?>
<package format='3'>
  <name>hpp_tools</name>
  <version>9.0.2</version>
  <description>Tools for the HPP project</description>
  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>LGPL-3.0-or-later</license>

  <url type='website'>http://github.com/humanoid-path-planner/hpp-tools</url>

  <depend>python3</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
 </package>
