HERE=`cd $(dirname ${BASH_SOURCE[0]}) && pwd`

export HPPCD_PATH="$HERE/hppcd"

[ -f "$HERE/bash/functions.sh" ] && source "$HERE/bash/functions.sh"
[ -f "$HERE/bash/aliases.sh" ] && source "$HERE/bash/aliases.sh"
